# Generated by Django 3.2.3 on 2022-12-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='a',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
