# Generated by Django 3.2.3 on 2022-12-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_calculator_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='a',
        ),
    ]
