# Generated by Django 3.2.3 on 2022-12-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_calculator_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculator',
            old_name='user',
            new_name='client',
        ),
    ]
