# Generated by Django 3.2.3 on 2022-12-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_rename_user_calculator_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculator',
            old_name='client',
            new_name='user',
        ),
    ]
