# Generated by Django 3.2.3 on 2022-12-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='calculator',
        ),
    ]
