# Generated by Django 4.1.5 on 2023-02-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
