# Generated by Django 4.1.5 on 2023-03-29 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 15, 37, 17, 133553)),
        ),
    ]
