# Generated by Django 4.1 on 2023-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageroom',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
