# Generated by Django 4.1 on 2023-03-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0002_alter_messageroom_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageRoom',
        ),
    ]
