# Generated by Django 4.1 on 2023-04-11 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0003_alter_messages_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 8, 20, 27, 830745)),
        ),
    ]
