# Generated by Django 4.1 on 2023-03-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatSystem', '0003_delete_messageroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message', models.TextField()),
                ('user', models.TextField()),
                ('roomId', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
