# Generated by Django 4.1 on 2023-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='roomId',
            field=models.TextField(),
        ),
    ]
