# Generated by Django 4.1 on 2023-03-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0005_messages_id_alter_messages_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='roomId',
            field=models.TextField(default=''),
        ),
    ]
