# Generated by Django 4.1 on 2023-04-18 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0005_alter_messages_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 8, 24, 40, 2905)),
        ),
    ]
