<<<<<<< HEAD
# Generated by Django 4.1 on 2023-04-18 12:24
=======
# Generated by Django 4.1.5 on 2023-04-14 17:25
>>>>>>> 6cef5f162f373d7e9703fe22d0cd030e908fb3d7

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0005_alter_messages_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='datetime',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 8, 24, 40, 2905)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 13, 25, 7, 612774)),
>>>>>>> 6cef5f162f373d7e9703fe22d0cd030e908fb3d7
        ),
    ]
