# Generated by Django 4.1.5 on 2023-04-14 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0005_alter_messages_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 13, 25, 7, 612774)),
        ),
    ]
