# Generated by Django 4.1 on 2023-03-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0006_alter_messages_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
