# Generated by Django 4.1 on 2023-04-19 14:28

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatSystem', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(default='Texas Instruments,Sharp,Casio,New,Used')),
            ],
        ),
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('locked', models.BooleanField(default=False)),
                ('users', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latestDateTime', models.DateTimeField(default=datetime.datetime(2023, 4, 19, 10, 28, 9, 607211))),
            ],
        ),
        migrations.CreateModel(
            name='TempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageRoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatSystem.messages')),
                ('message_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calcura.messageroom')),
            ],
        ),
        migrations.AddField(
            model_name='messageroom',
            name='messages',
            field=models.ManyToManyField(through='Calcura.MessageRoomMembership', to='chatSystem.messages'),
        ),
        migrations.AddField(
            model_name='messageroom',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageroom',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('tags', models.TextField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 4, 19, 10, 28, 9, 606212))),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
