# Generated by Django 4.1 on 2023-03-28 12:19

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(default='Texas Instruments,Sharp,Casio,New,Used')),
            ],
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('tags', models.TextField()),
                ('email', models.TextField()),
                ('fullname', models.TextField()),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 3, 28, 8, 19, 36, 384723))),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('users', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('email', models.TextField()),
            ],
        ),
    ]
