# Generated by Django 4.1.5 on 2023-01-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calcura',
        ),
    ]
