# Generated by Django 4.1.5 on 2023-04-14 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='imageNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageroom',
            name='locked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 13, 25, 7, 612774)),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='latestDateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 13, 25, 7, 612774)),
        ),
    ]
