# Generated by Django 4.1.5 on 2023-01-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Calcura', '0002_delete_calcura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('tags', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
