# Generated by Django 4.1 on 2023-04-11 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0002_alter_calculator_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 8, 20, 32, 417918)),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='latestDateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 8, 20, 32, 418916)),
        ),
    ]
