# Generated by Django 4.1.5 on 2023-03-29 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0002_alter_calculator_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 10, 21, 53, 604514)),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
