# Generated by Django 4.1.5 on 2023-02-03 14:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
