# Generated by Django 4.1 on 2023-04-18 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0004_alter_calculator_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='imageNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 8, 24, 40, 2905)),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='latestDateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 8, 24, 40, 4899)),
        ),
    ]
