# Generated by Django 4.1.5 on 2023-02-03 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0005_tempimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempimage',
            name='email',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculator',
            name='image',
            field=models.TextField(),
        ),
    ]
