# Generated by Django 4.1 on 2023-02-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0006_tempimage_email_alter_calculator_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='fullname',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
