# Generated by Django 4.1 on 2023-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0007_calculator_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(default='Texas Instruments,Sharp,Casio,New,Used')),
            ],
        ),
    ]
