# Generated by Django 4.1.5 on 2023-03-29 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0007_alter_calculator_datetime_alter_calculator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 11, 59, 31, 172576)),
        ),
    ]
