# Generated by Django 4.1 on 2023-03-03 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0008_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 9, 4, 45, 299099)),
        ),
    ]
