# Generated by Django 4.1.5 on 2023-03-29 16:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calcura', '0009_alter_calculator_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageroom',
            name='two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 12, 55, 1, 286130)),
        ),
    ]
