# Generated by Django 4.1.5 on 2023-03-29 19:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calcura', '0010_messageroom_one_messageroom_two_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='one',
        ),
        migrations.RemoveField(
            model_name='messageroom',
            name='two',
        ),
        migrations.AddField(
            model_name='messageroom',
            name='realUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 15, 25, 22, 168433)),
        ),
    ]
