# Generated by Django 4.1.5 on 2023-03-29 19:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calcura', '0012_remove_messageroom_realusers_messageroom_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageroom',
            old_name='two',
            new_name='user2',
        ),
        migrations.RemoveField(
            model_name='messageroom',
            name='one',
        ),
        migrations.AddField(
            model_name='messageroom',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 15, 30, 20, 770827)),
        ),
    ]
