# Generated by Django 4.1.5 on 2023-03-29 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0003_alter_messages_datetime'),
        ('Calcura', '0014_alter_calculator_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='messages',
            field=models.ManyToManyField(to='chatSystem.messages'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 15, 53, 7, 82354)),
        ),
    ]
