# Generated by Django 4.1.5 on 2023-03-30 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0015_messageroom_messages_alter_calculator_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='messages',
        ),
        migrations.AddField(
            model_name='messageroom',
            name='messageModal',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 20, 21, 1, 734765)),
        ),
    ]
