# Generated by Django 4.1 on 2023-03-23 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0015_alter_calculator_datetime_alter_calculator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 9, 11, 3, 347058)),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
