# Generated by Django 4.1.5 on 2023-03-30 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0016_remove_messageroom_messages_messageroom_messagemodal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 20, 23, 8, 717762)),
        ),
    ]
