# Generated by Django 4.1 on 2023-03-25 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0016_alter_calculator_datetime_alter_calculator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 12, 31, 31, 45773)),
        ),
    ]
