# Generated by Django 4.1.5 on 2023-03-30 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0006_alter_messages_datetime'),
        ('Calcura', '0017_alter_calculator_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='messageModal',
        ),
        migrations.AddField(
            model_name='messageroom',
            name='messages',
            field=models.ManyToManyField(default=(), limit_choices_to={'roomId': '<django.db.models.fields.BigAutoField>'}, to='chatSystem.messages'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 20, 25, 5, 708494)),
        ),
    ]
