# Generated by Django 4.1.5 on 2023-03-30 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0007_alter_messages_datetime'),
        ('Calcura', '0018_remove_messageroom_messagemodal_messageroom_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 20, 28, 32, 336912)),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='messages',
            field=models.ManyToManyField(default=(), to='chatSystem.messages'),
        ),
    ]
