# Generated by Django 4.1 on 2023-03-25 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0018_alter_calculator_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('users', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 12, 47, 51, 695037)),
        ),
    ]
