# Generated by Django 4.1.5 on 2023-03-30 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatSystem', '0008_alter_messages_datetime'),
        ('Calcura', '0019_alter_calculator_datetime_alter_messageroom_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 20, 59, 2, 814576)),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='messages',
            field=models.ManyToManyField(limit_choices_to={'roomId': models.BigAutoField(primary_key=True, serialize=False)}, to='chatSystem.messages'),
        ),
    ]
