# Generated by Django 4.1 on 2023-03-25 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcura', '0020_alter_calculator_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 13, 1, 32, 463213)),
        ),
    ]
